library(dplyr)
library(portalr)

#################################################
# TO DO:



#################################################

#' @title Get Rodent Data
#' 
#' @description make a data frame for running GAM models
#' 
#' @param startdate Census date of the period code used to filter the data
#' @param include_partial_census T/F: include censuses when some but not all 24 plots were trapped
#' 
#' @return data frame with columns:
#'            plot
#'            censusdate
#'            species
#'            abundance
#'            numericdate
#'            treatment (two letters representing before/after switch: C = control, E = krat exclosure, X = total rodent removal)


get_data = function(startdate = "2013-03-11", include_partial_census = F){
  data = portalr::abundance(path='repo', level = 'Plot', type='Granivores',
                            length="All", unknowns=TRUE, incomplete=TRUE,
                            shape="flat", time='date')
  data_tables = portalr::loadData('repo')
  trapping = data_tables[[3]]
  
  # identify partially trapped censuses
  if (include_partial_census == F) {
    incomplete = portalr::find_incomplete_censuses(trapping)
    # remove period 457 from this list of incomplete censuses: not all 24 plots were trapped, but all plots relevant to this project were
    incomplete = incomplete[!incomplete==457]
  } else {incomplete = c()}
  
  newmoons = data_tables[[4]]
  incomplete_censuses = filter(newmoons,period %in% incomplete)
  incomplete_censuses$censusdate = as.Date(incomplete_censuses$censusdate)
  
  data$species = as.character(data$species)
  data$numericdate = as.numeric(data$censusdate) / 1000
  rdat_filtered = dplyr::filter(data, censusdate >= startdate, !(censusdate %in% incomplete_censuses$censusdate))
  rdat_filtered = add_treatment(rdat_filtered) %>% arrange(censusdate)
  
  return(rdat_filtered)
}

#' @title Add treatment codes
#' 
#' @description adds treatment codes for each plot in the rodent dataframe
#' 
#' @param data dataframe must have a column named 'plot'
#' 
#' @return dataframe with columns:
#'            plot
#'            censusdate
#'            species
#'            abundance
#'            numericdate
#'            treatment (two letters representing before/after switch: C = control, E = krat exclosure, X = total rodent removal)
add_treatment = function(data){
  treatment = data.frame(treatment = c('CX','CE','EE','CC',
                                       'XC','EC','XC','CE',
                                       'CX','XX','CC','CX',
                                       'EC','CC','EE','XX',
                                       'CC','EC','EE','EE',
                                       'EE','CE','XX','XC'),plot=seq(1,24))
  data = merge(data,treatment)
  data = data %>% dplyr::filter(treatment %in% c('CC','XC','EC'))
  return(data)
}

#' @title Make Abundance Data
#'
#' @description make a data frame of rodent abundances for GAM models
#' 
#' @param species species desired; either "All," "Granivore," "Dipos," "SmGran," "SmH" (small heteromyid), or "SmM" (small murid)
#' @param dat name of dataframe holding dataframe generated by get_data()
#' 
#' @return data frame with columns:
#'            plot
#'            censusdate (date of data collection formatted YYYY-MM-DD)
#'            treatment (two letters representing before/after switch: C = control, E = krat exclosure, X = total rodent removal)
#'            n (number of individuals)
#'            Time (numeric version of censusdate for GAM analyses)

make_N_data= function(species='All', dat) {
  # Create species abundances by plot by period
  # select species of interest
  if (species=='All') {targetsp = c('BA','DM','DO','DS','NA','OL','OT','PB','PE','PF','PM','PP','RM','RO','SF','SH')}
  if (species=='Granivore') {targetsp = c('BA','DM','DO','DS','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO')}
  if (species=='SmGran') {targetsp = c('BA','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO')}
  if (species=='SmH') {targetsp = c('PB','PF','PH','PI','PP')}
  if (species=='SmM') {targetsp = c('BA','PE','PL','PM','RF','RM','RO')}
  if (species=='Dipos') {targetsp = c('DM','DO','DS')}
  if (species %in% unique(data$species)) {targetsp = species}
  
  target_dat = dplyr::filter(dat,species %in% targetsp)
  total = aggregate(target_dat$abundance,
                    by=list(plot=target_dat$plot,censusdate=target_dat$censusdate,
                            numericdate=target_dat$numericdate, 
                            treatment=target_dat$treatment),
                    FUN=sum)
  
  #total$x[is.na(total$x)] = 0
  # change column name
  total_gam = rename(total,n=x)
  # put data in chronological order
  total_gam = total_gam[order(total_gam$numericdate),]
  return(total_gam)
}


#' @title Average by treatment
#' 
#' @description Takes plot-level data and returns treatment-level
#' 
#' @param df data frame containing columns for censusdate, numericdate, treatment, n
#' 
avg_by_trt = function(df) {
  df_average = aggregate(df$n, by=list(censusdate = df$censusdate,
                                       numericdate = df$numericdate,
                                       treatment = df$treatment),FUN=mean)
  df_average = dplyr::rename(df_average,n=x)
  return(df_average)
}


#' @title Count positive values
#' 
#' @description Counts the number of non-zero integers in a vector
#' 
#' @param x a vector of integers
#' 
#' @return an integer value
count_integers = function(x){
  values_greater_zero = sum(x > 0)
  return(values_greater_zero)
}

#' @title Species richness
#' 
#' @description get species richness at period and plot level
#' 
#' @param rdat rodent data; column abundance, numericdate, plot, censusdate, treatment
#' 
#' @return data frame with numericdate, plot, censusdate, treatment, n

make_speciesrich_data = function(dat) {
  
  # count number of species in rodent data
  richness = aggregate(dat$abundance,
                       by=list(numericdate=dat$numericdate,plot=dat$plot, 
                               censusdate=dat$censusdate, treatment=dat$treatment),
                       FUN=count_integers)
  # put data in chronological order
  richness = richness[order(richness$numericdate),]
  richness = dplyr::rename(richness,n=x)
  return(richness)
}


##### Below this point is code that has not been rectified with portalr.
##### This is because portalr does not have biomass functions yet and
##### because we decided not to do eveness, but I haven't removed the code yet.

#' @title get mass data
#' 
#' @description get total or average rodent mass by period and plot
#'
#' @param start_period first period number of data desired; default is 130 (1989)
#' @param avg T/F: if true, computes average wgt per plot, if F computes total wgt
#' @param metE T/F: if T converts mass to metabolic energy, if F returns mass data
#' 
#' @example avg_mass = get_mass(start_period = 415,avg=T)
#'
#'
#' get_mass = function(start_period=130, avg, metE) {
#'   # load rodent data
#'   rdat_filtered = filter_data(start_period,incomplete=F) %>% select(period,plot,species,wgt)
#'   
#'   # fill in unweighed rodents with avg mass for that species
#'   avgmass = aggregate(rdat_filtered$wgt, by = list(species = rdat_filtered$species),FUN=mean,na.rm=T)
#'   rdat_filtered = merge(rdat_filtered,avgmass)
#'   for (n in seq(length(rdat_filtered$species))) {
#'     if (is.na(rdat_filtered$wgt[n])) {
#'       rdat_filtered$wgt[n] = rdat_filtered$x[n]
#'     }
#'   }
#'   
#'   # convert mass to metabolic energy if desired
#'   if (metE == T) {
#'     rdat_filtered$wgt = 5.69 * rdat_filtered$wgt^0.75
#'   }
#'   
#'   # get either total or average mass per plot and period
#'   if (avg == T) {
#'     mass = aggregate(rdat_filtered$wgt,by=list(period=rdat_filtered$period,plot=rdat_filtered$plot),FUN=mean)
#'   } else {
#'     mass = aggregate(rdat_filtered$wgt,by=list(period=rdat_filtered$period,plot=rdat_filtered$plot),FUN=sum)
#'   }
#'   
#'   # change column name
#'   mass = rename(mass,n=x)
#'   
#'   # data frame of all plots in all periods
#'   allplotsperiod = expand.grid(period=unique(rdat_filtered$period), plot=unique(rdat_filtered$plot))
#'   #attach date columns according to period
#'   allplotsperiod = append_dates(allplotsperiod)
#'   # attach treatment column according to plot number
#'   treatment = data.frame(treatment = c('CX','CE','EE','CC',
#'                                        'XC','EC','XC','CE',
#'                                        'CX','XX','CC','CX',
#'                                        'EC','CC','EE','XX',
#'                                        'CC','EC','EE','EE',
#'                                        'EE','CE','XX','XC'),plot=seq(1,24))
#'   allplotsperiod = merge(allplotsperiod,treatment)
#'   # merge capture data with data frame of all plots and all periods, and fill in empty data with zeros
#'   mass_data = merge(allplotsperiod,mass,all=T)
#'   mass_data$n[is.na(mass_data$n)] = 0
#'   # put data in chronological order
#'   mass_data = mass_data[order(mass_data$period),]
#'   return(mass_data)
#' }
#' 
#' #' @title get species evenness
#' #' 
#' #' @description calculate species evenness per plot/period
#' #' 
#' #' @param start_period first period number of data desired
#' #' 
#' get_evenness = function(start_period=415) {
#'   # load rodent data
#'   rdat_filtered = filter_data(start_period,incomplete=F) %>% select('period','plot','species')
#'   
#'   # put data in tabular form
#'   rdat_filtered$periodplot = paste(rdat_filtered$period,rdat_filtered$plot)
#'   plt_table = table(rdat_filtered$periodplot,rdat_filtered$species)
#' 
#'   # calculate Shannon diversity and evenness
#'   H = vegan::diversity(plt_table)
#'   even = H/log(vegan::specnumber(plt_table))
#'   
#'   evenness = data.frame(periodplot = names(even), n = unname(even))
#'   evenness$periodplot = as.character(evenness$periodplot)
#'   evenness$period = rep(NA)
#'   evenness$plot = rep(NA)
#'   for (ind in seq(length(evenness$periodplot))) {
#'     evenness$period[ind] = strsplit(evenness$periodplot,' ')[[ind]][1]
#'     evenness$plot[ind] = strsplit(evenness$periodplot,' ')[[ind]][2]
#'   }
#'   # append date columns
#'   evenness_dat = evenness %>% select(-periodplot) %>% append_dates()
#'   # attach treatment column according to plot number
#'   treatment = data.frame(treatment = c('CX','CE','EE','CC',
#'                                        'XC','EC','XC','CE',
#'                                        'CX','XX','CC','CX',
#'                                        'EC','CC','EE','XX',
#'                                        'CC','EC','EE','EE',
#'                                        'EE','CE','XX','XC'),plot=seq(1,24))
#'   evenness_dat = merge(evenness_dat,treatment)
#'   # put rows in chronological order
#'   evenness_dat = evenness_dat[order(evenness_dat$period),]
#'   
#'   return(evenness_dat)
#' }

