library(dplyr)
library(portalr)

#################################################
# TO DO:



#################################################

#' @title Get Rodent Data
#' 
#' @description make a data frame for running GAM models
#' 
#' @param startdate Census date of the period code used to filter the data
#' @param min_num_plots integer 1-24: input for abundance() function in portalr (how many plots for a census to be considered complete)
#'                                    24 is all plots(special case period 457: only 21 plots trapped but all CC, EC, and XC were trapped)
#' @param treatments which treatments to include in output (choices are 'CC','EC','XC','CE','EE','XE','CX','XX')
#' 
#' @return data frame with columns:
#'            plot
#'            censusdate
#'            species
#'            abundance
#'            numericdate
#'            treatment (two letters representing before/after switch: C = control, E = krat exclosure, X = total rodent removal)


get_data = function(startdate = "2013-03-11",min_num_plots=24, treatments = 'all'){
  data = portalr::abundance(path='..', level = 'Plot', type='Granivores',
                            length="All", unknowns=FALSE, min_plots = min_num_plots,
                            shape="flat", time='date',clean=F,na_drop=T)
  
  data$species = as.character(data$species)
  data$numericdate = as.numeric(data$censusdate) / 1000
  rdat_filtered = dplyr::filter(data, censusdate >= startdate)
  rdat_filtered = add_treatment(rdat_filtered) %>% arrange(censusdate)
  rdat_filtered = rdat_filtered %>% dplyr::filter(before_after %in% treatments)
  
  return(rdat_filtered)
}

#' @title find incomplete censuses
#'
#' @description finds censuses where not all plots were trapped: for this project only, census 457 is complete (all plots relevant here were trapped)
#'  
# find_incomplete_censuses_plotswitch = function() {
#   data_tables = portalr::load_data('..',clean=F)
#   trapping = data_tables[[3]]
#   
#   # identify partially trapped censuses
#   incomplete = portalr::find_incomplete_censuses(trapping)
#   # remove period 457 from this list of incomplete censuses: not all 24 plots were trapped, but all plots relevant to this project were
#   incomplete = incomplete[!incomplete==457]
#   
#   newmoons = data_tables[[4]]
#   incomplete_censuses = filter(newmoons,period %in% incomplete)
#   incomplete_censuses$censusdate = as.Date(incomplete_censuses$censusdate)
#   return(incomplete_censuses)
# }

#' @title Add treatment codes
#' 
#' @description adds treatment codes for each plot in the rodent dataframe
#' 
#' @param data dataframe must have a column named 'plot'
#' 
#' @return dataframe with columns:
#'            plot
#'            censusdate
#'            species
#'            abundance
#'            numericdate
#'            before_after (two letters representing before/after switch: C = control, E = krat exclosure, X = total rodent removal)
add_treatment = function(data){
  treatment = data.frame(before_after = c('CX','CE','EE','CC',
                                       'XC','EC','XC','CE',
                                       'CX','XX','CC','CX',
                                       'EC','CC','EE','XX',
                                       'CC','EC','EE','EE',
                                       'EE','CE','XX','XC'),plot=seq(1,24))
  data = merge(data,treatment,by='plot')
  
  return(data)
}

#' @title Make Abundance Data
#'
#' @description make a data frame of rodent abundances for GAM models
#' 
#' @param species species desired; either "All," "Granivore," "Dipos," "SmGran," "SmH" (small heteromyid), or "SmM" (small murid)
#' @param dat name of dataframe holding dataframe generated by get_data()
#' 
#' @return data frame with columns:
#'            plot
#'            censusdate (date of data collection formatted YYYY-MM-DD)
#'            treatment (two letters representing before/after switch: C = control, E = krat exclosure, X = total rodent removal)
#'            n (number of individuals)
#'            Time (numeric version of censusdate for GAM analyses)

make_N_data= function(species='All', dat) {
  # Create species abundances by plot by period
  # select species of interest
  if (species=='All') {targetsp = c('BA','DM','DO','DS','NA','OL','OT','PB','PE','PF','PM','PP','RM','RO','SF','SH')}
  if (species=='Granivore') {targetsp = c('BA','DM','DO','DS','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO')}
  if (species=='SmGran') {targetsp = c('BA','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO')}   #{targetsp = c('PB','PE','PF','PM','PP','RM')}
  if (species=='SmH') {targetsp = c('PB','PF','PH','PI','PP')}
  if (species=='SmM') {targetsp = c('BA','PE','PL','PM','RF','RM','RO')}
  if (species=='Dipos') {targetsp = c('DM','DO','DS')}
  if (species %in% unique(dat$species)) {targetsp = species}
  
  target_dat = dplyr::filter(dat,species %in% targetsp)
  total = aggregate(target_dat$abundance,
                    by=list(plot=target_dat$plot,
                            censusdate=target_dat$censusdate,
                            numericdate=target_dat$numericdate, 
                            treatment=target_dat$before_after),
                    FUN=sum)
  
  # change column name
  total_gam = dplyr::rename(total,n=x)
  # put data in chronological order
  total_gam = total_gam[order(total_gam$numericdate),]
  return(total_gam)
}


#' @title Average by treatment
#' 
#' @description Takes plot-level data and returns treatment-level
#' 
#' @param df data frame containing columns for censusdate, numericdate, treatment, n
#' 
avg_by_trt = function(df) {
  df_average = aggregate(df$n, by=list(censusdate = df$censusdate,
                                       numericdate = df$numericdate,
                                       treatment = df$treatment),FUN=mean)
  df_average = dplyr::rename(df_average,n=x)
  return(df_average)
}


#' @title Count positive values
#' 
#' @description Counts the number of non-zero integers in a vector
#' 
#' @param x a vector of integers
#' 
#' @return an integer value
count_integers = function(x){
  values_greater_zero = sum(x > 0)
  return(values_greater_zero)
}

#' @title Species richness
#' 
#' @description get species richness at period and plot level
#' 
#' @param rdat rodent data; column abundance, numericdate, plot, censusdate, treatment
#' 
#' @return data frame with numericdate, plot, censusdate, treatment, n

make_speciesrich_data = function(dat) {
  # remove species == other 
  dat = filter(dat,species != 'other')
  
  # count number of species in rodent data
  richness = aggregate(dat$abundance,
                       by=list(numericdate=dat$numericdate,plot=dat$plot, 
                               censusdate=dat$censusdate, treatment=dat$before_after),
                       FUN=count_integers)
  # put data in chronological order
  richness = richness[order(richness$numericdate),]
  richness = dplyr::rename(richness,n=x)
  # rearrange columns
  richness = richness[,c('plot','censusdate','numericdate','treatment','n')]
  return(richness)
}

#' @title community energy by date
#' 
#' @param startdate Census date of the period code used to filter the data
#' @param min_num_plots integer 1-24: input for abundance() function in portalr (how many plots for a census to be considered complete)
#'                                    24 is all plots(special case period 457: only 21 plots trapped but all CC, EC, and XC were trapped)
#' @param species 
#' 
get_community_energy = function(startdate = "2013-03-11", min_num_plots = 24,species='Granivore') {
  # select species of interest
  if (species=='All') {targetsp = c('BA','DM','DO','DS','NA','OL','OT','PB','PE','PF','PM','PP','RM','RO','SF','SH')}
  if (species=='Granivore') {targetsp = c('BA','DM','DO','DS','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO')}
  if (species=='SmGran') {targetsp = c('BA','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO')}   #{targetsp = c('PB','PE','PF','PM','PP','RM')}
  if (species=='SmH') {targetsp = c('PB','PF','PH','PI','PP')}
  if (species=='SmM') {targetsp = c('BA','PE','PL','PM','RF','RM','RO')}
  if (species=='Dipos') {targetsp = c('DM','DO','DS')}
  if (species %in% unique(dat$species)) {targetsp = species}
  
  energydat = portalr::get_rodent_data(path='..', level = 'Plot', type='Rodents',
                                       length="All", unknowns=FALSE, min_plots=min_num_plots,
                                       shape="flat", time='date',clean=F,output='energy',
                                       fillweight = T,na_drop=T)
  
  energydat$numericdate = as.numeric(energydat$censusdate) / 1000
  energydat_filtered = dplyr::filter(energydat, censusdate >= startdate, species %in% targetsp)
  energydat_filtered = add_treatment(energydat_filtered) %>% arrange(censusdate)
  
  # sum by date and plot
  energy_byplot = aggregate(energydat_filtered$energy,by=list(plot = energydat_filtered$plot,
                                                              censusdate = energydat_filtered$censusdate,
                                                              numericdate = energydat_filtered$numericdate,
                                                              treatment = energydat_filtered$before_after),
                            FUN=sum)
  # put in chronological order
  energy_byplot = energy_byplot[order(energy_byplot$numericdate),]
  energy_byplot = dplyr::rename(energy_byplot,energy=x)
  return(energy_byplot)
}

#' @title 3 month average
#' @description calculates 3 month average of period-resolution data
#' 
#' @param df data frame: must include 'censusdate' and 'n' columns
#'
#'
avg_3month = function(df) {
  df$month = format(df$censusdate,'%m')
  df$year = format(df$censusdate,'%Y')
  df$quarter = rep(NA)
  df$quarter[df$month %in% c('01','02','03')] <- 0
  df$quarter[df$month %in% c('04','05','06')] <- .25
  df$quarter[df$month %in% c('07','08','09')] <- .5
  df$quarter[df$month %in% c('10','11','12')] <- .75
  quarterly = aggregate(df$n,by=list(plot=df$plot,treatment=df$treatment,quarter=df$quarter,year=df$year),FUN=mean)
  quarterly$censusdate = as.numeric(quarterly$year)+quarterly$quarter
  quarterly = plyr::rename(quarterly,c("x"="n"))
  return(quarterly)
}


##### Below this point is code that has not been rectified with portalr.
##### This is because portalr does not have biomass functions yet and
##### because we decided not to do eveness, but I haven't removed the code yet.

#' @title get mass data
#' 
#' @description get total or average rodent mass by period and plot
#'
#' @param start_period first period number of data desired; default is 130 (1989)
#' @param avg T/F: if true, computes average wgt per plot, if F computes total wgt
#' @param metE T/F: if T converts mass to metabolic energy, if F returns mass data
#' 
#' @example avg_mass = get_mass(start_period = 415,avg=T)
#'
#'
#' get_mass = function(start_period=130, avg, metE) {
#'   # load rodent data
#'   rdat_filtered = filter_data(start_period,incomplete=F) %>% select(period,plot,species,wgt)
#'   
#'   # fill in unweighed rodents with avg mass for that species
#'   avgmass = aggregate(rdat_filtered$wgt, by = list(species = rdat_filtered$species),FUN=mean,na.rm=T)
#'   rdat_filtered = merge(rdat_filtered,avgmass)
#'   for (n in seq(length(rdat_filtered$species))) {
#'     if (is.na(rdat_filtered$wgt[n])) {
#'       rdat_filtered$wgt[n] = rdat_filtered$x[n]
#'     }
#'   }
#'   
#'   # convert mass to metabolic energy if desired
#'   if (metE == T) {
#'     rdat_filtered$wgt = 5.69 * rdat_filtered$wgt^0.75
#'   }
#'   
#'   # get either total or average mass per plot and period
#'   if (avg == T) {
#'     mass = aggregate(rdat_filtered$wgt,by=list(period=rdat_filtered$period,plot=rdat_filtered$plot),FUN=mean)
#'   } else {
#'     mass = aggregate(rdat_filtered$wgt,by=list(period=rdat_filtered$period,plot=rdat_filtered$plot),FUN=sum)
#'   }
#'   
#'   # change column name
#'   mass = rename(mass,n=x)
#'   
#'   # data frame of all plots in all periods
#'   allplotsperiod = expand.grid(period=unique(rdat_filtered$period), plot=unique(rdat_filtered$plot))
#'   #attach date columns according to period
#'   allplotsperiod = append_dates(allplotsperiod)
#'   # attach treatment column according to plot number
#'   treatment = data.frame(treatment = c('CX','CE','EE','CC',
#'                                        'XC','EC','XC','CE',
#'                                        'CX','XX','CC','CX',
#'                                        'EC','CC','EE','XX',
#'                                        'CC','EC','EE','EE',
#'                                        'EE','CE','XX','XC'),plot=seq(1,24))
#'   allplotsperiod = merge(allplotsperiod,treatment)
#'   # merge capture data with data frame of all plots and all periods, and fill in empty data with zeros
#'   mass_data = merge(allplotsperiod,mass,all=T)
#'   mass_data$n[is.na(mass_data$n)] = 0
#'   # put data in chronological order
#'   mass_data = mass_data[order(mass_data$period),]
#'   return(mass_data)
#' }
#' 
#' #' @title get species evenness
#' #' 
#' #' @description calculate species evenness per plot/period
#' #' 
#' #' @param start_period first period number of data desired
#' #' 
#' get_evenness = function(start_period=415) {
#'   # load rodent data
#'   rdat_filtered = filter_data(start_period,incomplete=F) %>% select('period','plot','species')
#'   
#'   # put data in tabular form
#'   rdat_filtered$periodplot = paste(rdat_filtered$period,rdat_filtered$plot)
#'   plt_table = table(rdat_filtered$periodplot,rdat_filtered$species)
#' 
#'   # calculate Shannon diversity and evenness
#'   H = vegan::diversity(plt_table)
#'   even = H/log(vegan::specnumber(plt_table))
#'   
#'   evenness = data.frame(periodplot = names(even), n = unname(even))
#'   evenness$periodplot = as.character(evenness$periodplot)
#'   evenness$period = rep(NA)
#'   evenness$plot = rep(NA)
#'   for (ind in seq(length(evenness$periodplot))) {
#'     evenness$period[ind] = strsplit(evenness$periodplot,' ')[[ind]][1]
#'     evenness$plot[ind] = strsplit(evenness$periodplot,' ')[[ind]][2]
#'   }
#'   # append date columns
#'   evenness_dat = evenness %>% select(-periodplot) %>% append_dates()
#'   # attach treatment column according to plot number
#'   treatment = data.frame(treatment = c('CX','CE','EE','CC',
#'                                        'XC','EC','XC','CE',
#'                                        'CX','XX','CC','CX',
#'                                        'EC','CC','EE','XX',
#'                                        'CC','EC','EE','EE',
#'                                        'EE','CE','XX','XC'),plot=seq(1,24))
#'   evenness_dat = merge(evenness_dat,treatment)
#'   # put rows in chronological order
#'   evenness_dat = evenness_dat[order(evenness_dat$period),]
#'   
#'   return(evenness_dat)
#' }

