library(dplyr)
library(portalr)

## install older version of portalr if necessary
# require(devtools)
# install_version('portalr', version = '0.1.4')
# install_version('portalr', version = '0.2.6')



#' @title Get Rodent Data
#' 
#' @description make a data frame for running GAM models
#' 
#' @param startdate Census date of the period code used to filter the data
#' @param min_num_plots integer 1-24: input for abundance() function in portalr (how many plots for a census to be considered complete)
#'                                    24 is all plots(special case period 457: only 21 plots trapped but all CC, EC, and XC were trapped)
#' @param treatments which treatments to include in output (choices are 'CC','EC','XC','CE','EE','XE','CX','XX')
#' @param data_folder path to folder where PortalData repo was downloaded into
#' 
#' @return data frame with columns:
#'            plot
#'            censusdate
#'            species
#'            abundance
#'            numericdate
#'            treatment (two letters representing before/after switch: C = control, E = krat exclosure, X = total rodent removal)

get_data = function(startdate = "2013-03-11",min_num_plots=24, treatments = 'all', data_folder = '.'){
  data = portalr::abundance(path=data_folder, level = 'Plot', type='Granivores',
                            plots='all', unknowns=FALSE, min_plots = min_num_plots,
                            shape="flat", time='date',clean=F,na_drop=T)
  
  data$species = as.character(data$species)
  data$numericdate = as.numeric(data$censusdate) / 1000
  rdat_filtered = dplyr::filter(data, censusdate >= startdate)
  rdat_filtered = add_treatment(rdat_filtered) %>% arrange(censusdate)
  rdat_filtered = rdat_filtered %>% dplyr::filter(before_after %in% treatments)
  
  return(rdat_filtered)
}

#' @title find incomplete censuses
#'
#' @description finds censuses where not all plots were trapped: for this project only, census 457 is complete (all plots relevant here were trapped)
#'  
# find_incomplete_censuses_plotswitch = function() {
#   data_tables = portalr::load_data('..',clean=F)
#   trapping = data_tables[[3]]
#   
#   # identify partially trapped censuses
#   incomplete = portalr::find_incomplete_censuses(trapping)
#   # remove period 457 from this list of incomplete censuses: not all 24 plots were trapped, but all plots relevant to this project were
#   incomplete = incomplete[!incomplete==457]
#   
#   newmoons = data_tables[[4]]
#   incomplete_censuses = filter(newmoons,period %in% incomplete)
#   incomplete_censuses$censusdate = as.Date(incomplete_censuses$censusdate)
#   return(incomplete_censuses)
# }

#' @title Add treatment codes
#' 
#' @description adds treatment codes for each plot in the rodent dataframe
#' 
#' @param data dataframe must have a column named 'plot'
#' 
#' @return dataframe with columns:
#'            plot
#'            censusdate
#'            species
#'            abundance
#'            numericdate
#'            before_after (two letters representing before/after switch: C = control, E = krat exclosure, X = total rodent removal)
add_treatment = function(data){
  treatment = data.frame(before_after = c('CX','CE','EE','CC',
                                       'XC','EC','XC','CE',
                                       'CX','XX','CC','CX',
                                       'EC','CC','EE','XX',
                                       'CC','EC','EE','EE',
                                       'EE','CE','XX','XC'),plot=seq(1,24))
  data = merge(data,treatment,by='plot')
  
  return(data)
}

#' @title Make Abundance Data
#'
#' @description make a data frame of rodent abundances for GAM models
#' 
#' @param species species desired; either "All," "Granivore," "Dipos," "SmGran," "SmH" (small heteromyid), or "SmM" (small murid)
#' @param dat name of dataframe holding dataframe generated by get_data()
#' 
#' @return data frame with columns:
#'            plot
#'            censusdate (date of data collection formatted YYYY-MM-DD)
#'            treatment (two letters representing before/after switch: C = control, E = krat exclosure, X = total rodent removal)
#'            n (number of individuals)
#'            Time (numeric version of censusdate for GAM analyses)

make_N_data= function(species='All', dat) {
  # Create species abundances by plot by period
  # select species of interest
  if (species=='All') {targetsp = c('BA','DM','DO','DS','NA','OL','OT','PB','PE','PF','PM','PP','RM','RO','SF','SH')}
  if (species=='Granivore') {targetsp = c('BA','DM','DO','DS','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO')}
  if (species=='SmGran') {targetsp = c('BA','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO')}   
  if (species=='SmH') {targetsp = c('PB','PF','PH','PI','PP')}
  if (species=='SmM') {targetsp = c('BA','PE','PL','PM','RF','RM','RO')}
  if (species=='Dipos') {targetsp = c('DM','DO','DS')}
  if (species %in% unique(dat$species)) {targetsp = species}
  if (species=='SmCore') {targetsp = c('PB','PE','PF','PP','RM')}
  if (species=='SmTemp') {targetsp = c('BA','PL','PM','RF','RO')}
  
  target_dat = dplyr::filter(dat,species %in% targetsp)
  total = aggregate(target_dat$abundance,
                    by=list(plot=target_dat$plot,
                            censusdate=target_dat$censusdate,
                            numericdate=target_dat$numericdate, 
                            treatment=target_dat$before_after),
                    FUN=sum)
  
  # change column name
  total_gam = dplyr::rename(total,n=x)
  # put data in chronological order
  total_gam = total_gam[order(total_gam$numericdate),]
  return(total_gam)
}


#' @title Average by treatment
#' 
#' @description Takes plot-level data and returns treatment-level
#' 
#' @param df data frame containing columns for censusdate, numericdate, treatment, n
#' 
avg_by_trt = function(df) {
  df_average = aggregate(df$n, by=list(censusdate = df$censusdate,
                                       numericdate = df$numericdate,
                                       treatment = df$treatment),FUN=mean)
  df_average = dplyr::rename(df_average,n=x)
  return(df_average)
}


#' @title Count positive values
#' 
#' @description Counts the number of non-zero integers in a vector
#' 
#' @param x a vector of integers
#' 
#' @return an integer value
count_integers = function(x){
  values_greater_zero = sum(x > 0)
  return(values_greater_zero)
}

#' @title Species richness
#' 
#' @description get species richness at period and plot level
#' 
#' @param rdat rodent data; column abundance, numericdate, plot, censusdate, treatment
#' 
#' @return data frame with numericdate, plot, censusdate, treatment, n

make_speciesrich_data = function(dat) {
  # remove species == other 
  dat = filter(dat,species != 'other')
  
  # count number of species in rodent data
  richness = aggregate(dat$abundance,
                       by=list(numericdate=dat$numericdate,plot=dat$plot, 
                               censusdate=dat$censusdate, treatment=dat$before_after),
                       FUN=count_integers)
  # put data in chronological order
  richness = richness[order(richness$numericdate),]
  richness = dplyr::rename(richness,n=x)
  # rearrange columns
  richness = richness[,c('plot','censusdate','numericdate','treatment','n')]
  return(richness)
}

#' @title community energy by date
#' 
#' @param path path where PortalData was downloaded
#' @param startdate Census date of the period code used to filter the data
#' @param min_num_plots integer 1-24: input for abundance() function in portalr (how many plots for a census to be considered complete)
#'                                    24 is all plots(special case period 457: only 21 plots trapped but all CC, EC, and XC were trapped)
#' @param species 
#' 
get_community_energy = function(path='.', startdate = "2013-03-11", min_num_plots = 24,species='Granivore') {
  # select species of interest
  if (species=='All') {targetsp = c('BA','DM','DO','DS','NA','OL','OT','PB','PE','PF','PM','PP','RM','RO','SF','SH')}
  if (species=='Granivore') {targetsp = c('BA','DM','DO','DS','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO')}
  if (species=='SmGran') {targetsp = c('BA','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO')}   #{targetsp = c('PB','PE','PF','PM','PP','RM')}
  if (species=='SmH') {targetsp = c('PB','PF','PH','PI','PP')}
  if (species=='SmM') {targetsp = c('BA','PE','PL','PM','RF','RM','RO')}
  if (species=='Dipos') {targetsp = c('DM','DO','DS')}
  if (species %in% unique(dat$species)) {targetsp = species}
  
  energydat = portalr::summarize_rodent_data(path=path, level = 'Plot', type='Rodents',
                                             plots="All", unknowns=FALSE, min_plots=min_num_plots,
                                             shape="flat", time='date',clean=F,output='energy',
                                             fillweight = T,na_drop=T)
  
  energydat$numericdate = as.numeric(energydat$censusdate) / 1000
  energydat_filtered = dplyr::filter(energydat, censusdate >= startdate, species %in% targetsp)
  energydat_filtered = add_treatment(energydat_filtered) %>% arrange(censusdate)
  
  # sum by date and plot
  energy_byplot = aggregate(energydat_filtered$energy,by=list(plot = energydat_filtered$plot,
                                                              censusdate = energydat_filtered$censusdate,
                                                              numericdate = energydat_filtered$numericdate,
                                                              treatment = energydat_filtered$before_after),
                            FUN=sum)
  # put in chronological order
  energy_byplot = energy_byplot[order(energy_byplot$numericdate),]
  energy_byplot = dplyr::rename(energy_byplot,n=x)
  return(energy_byplot)
}

#' @title 3 month average
#' @description calculates 3 month average of period-resolution data
#' 
#' @param df data frame: must include 'censusdate' and 'n' columns
#'
#'
avg_3month = function(df) {
  df$month = format(df$censusdate,'%m')
  df$year = format(df$censusdate,'%Y')
  df$quarter = rep(NA)
  df$quarter[df$month %in% c('01','02','03')] <- 0
  df$quarter[df$month %in% c('04','05','06')] <- .25
  df$quarter[df$month %in% c('07','08','09')] <- .5
  df$quarter[df$month %in% c('10','11','12')] <- .75
  quarterly = aggregate(df$n,by=list(plot=df$plot,treatment=df$treatment,quarter=df$quarter,year=df$year),FUN=mean)
  quarterly$censusdate = as.numeric(quarterly$year)+quarterly$quarter
  quarterly = plyr::rename(quarterly,c("x"="n"))
  return(quarterly)
}

#' @title get winter or summer plant data: crosstab
#'
#' @param path path where PortalData was downloaded
#' @param selected_plots plot numbers: 1-24
#' @param plant_community which plant community (e.g. annuals or perennials; input 'type' in plant_abundance function)
#' @param summer_winter 'summer' or 'winter' census; or "both" for perennials
#' @param threshold value used to remove "rare" or "transient" species from the table. For example, a threshold of .1 removes species that are present in less than 10% of sampling years
#'
#' @return table of plant counts by species
#'
make_plant_table = function(path='.',selected_plots,plant_community,summer_winter,threshold=0.1) {
  plant_data = portalr::plant_abundance(path,level='Plot',type=plant_community,
                                        correct_sp=T,unknowns=F,plots=selected_plots,
                                        shape='flat')
  
  # remove data before 1983 to avoid having to adjust by quadrat area per plot
  season_data = dplyr::filter(plant_data,year>1982, season==summer_winter)

  # find species that occurred in <10% of years
  transients = find_transient_species(season_data,threshold)
  
  # filter based on selected_plots, remove transient species
  seasonplants = dplyr::filter(season_data,plot %in% selected_plots, !(species %in% transients$species))
  
  # sum by year (effort doesn't vary by year)
  seasontotal = aggregate(seasonplants$abundance,by=list(year=seasonplants$year,season=seasonplants$season,species=seasonplants$species,plot=seasonplants$plot),FUN=sum)
  seasontable = portalr:::make_crosstab(seasontotal,variable_name='x')
  seasontable[is.na(seasontable)] <- 0
  
  
  return(seasontable)
}

#' @title find transient species
#'
#' @description identifies species found in less than a given percentage of sampling events
#'
#' @param data_table table of data including species and year
#' @param threshold value for determining transient. Default 10%
#' 
#' @return vector of species names that are rare
#'
find_transient_species = function(data_table,threshold=0.1) {
  data_table = dplyr::ungroup(data_table)
  ntimesteps = dplyr::select(data_table,year) %>% unique() %>% nrow()
  sp_time = dplyr::select(data_table,year,species) %>% unique()
  yrs_present = dplyr::count(sp_time,species)
  transient_names = dplyr::filter(yrs_present,n <= threshold*ntimesteps) %>% dplyr::select(species)
  return(transient_names)
}


#' @title make treatment table
#' @description make table of plot numbers and treatment before/after switch
#' 
make_treatment_table = function() {
  
  treat_table = data.frame(plot=1:24,
                           treat_before = rep(NA),
                           treat_after = rep(NA),
                           flip_type = rep(NA))
  
  treat_table$treat_before[treat_table$plot %in% c(1,2,4,8,9,11,12,14,17,22)] <- 'control'
  treat_table$treat_before[treat_table$plot %in% c(3,6,13,15,18,19,20,21)] <- 'exclosure'
  treat_table$treat_before[treat_table$plot %in% c(5,7,10,16,23,24)] <- 'removal'
  
  treat_table$treat_after[treat_table$plot %in% c(4,5,6,7,11,13,14,17,18,24)] <- 'control'
  treat_table$treat_after[treat_table$plot %in% c(2,3,8,15,19,20,21,22)] <- 'exclosure'
  treat_table$treat_after[treat_table$plot %in% c(1,9,10,12,16,23)] <- 'removal'
  
  treat_table$flip_type[treat_table$plot %in% c(4,11,14,17)] <- 'control'
  treat_table$flip_type[treat_table$plot %in% c(3,15,19,20,21)] <- 'exclosure'
  treat_table$flip_type[treat_table$plot %in% c(10,16,23)] <- 'removal'
  treat_table$flip_type[treat_table$plot %in% c(2,8,22)] <- 'control-exclosure'
  treat_table$flip_type[treat_table$plot %in% c(6,13,18)] <- 'exclosure-control'
  treat_table$flip_type[treat_table$plot %in% c(5,7,24)] <- 'removal-control'
  treat_table$flip_type[treat_table$plot %in% c(1,12,9)] <- 'control-removal'
  return(treat_table)
}